import ast
from fnmatch import fnmatch
from pathlib import Path

GENERATED_FILE_PATTERNS = [
    "generated.py",
    "generated_*.py",
    "*_generated.py",
    "**generated**.py",
    "autogenerated.py",
    "autogenerated_*.py",
    "*_autogenerated.py",
    "**autogenerated**.py",
    "auto_generated.py",
    "auto_generated_*.py",
    "*_auto_generated.py",
    "**auto_generated**.py",
    "autogen.py",
    "autogen_*.py",
    "*_autogen.py",
    "**autogen**.py",
    "codegen.py",
    "codegen_*.py",
    "*_codegen.py",
    "**codegen**.py",
    "code_generated.py",
    "code_generated_*.py",
    "*_code_generated.py",
    "gen.py",
    "gen_*.py",
    "*_gen.py",
    "*_generated_code.py",
]

def is_generated(path: Path) -> bool:
    """Return True when a Python file matches a generated-file pattern."""
    filename = path.name
    return any(fnmatch(filename, pattern) for pattern in GENERATED_FILE_PATTERNS)