ignore_paths = ['tests']

[limits]
max_parameters = 22
max_nesting = 22
max_function_lines = 1262
max_class_lines = 4746
max_file_lines = 16897
max_complexity = 539
max_boolean_conditions = 10
max_if_chain = 17
max_local_variables = 46
max_return_statements = 34
max_lambda_nodes = 49
max_large_comprehensions = 83

[rules]
max_parameters = true
max_nesting = true
max_function_lines = true
max_class_lines = true
max_file_lines = true
max_complexity = true
max_boolean_conditions = true
max_local_variables = true
max_return_statements = true
max_lambda_nodes = true
max_large_comprehensions = true
mutable_default_args = true
